const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{background_netral: 0},
	{papan_main_menu: 0},
	{main: 0},
	{panduan: 0},
	{hasil_belajar: 0},
	{tentang_media: 0},
	{keluar: 0},
	{pusat_bantuan: 0},
	{gembok: 0},
	{icon_akun: 0},
	{nama_profile: 0},
	{peringkat: 0},
	{pengaturan: 0},
	{pesan: 0},
	{background_netral_1: 0},
	{background_panduan: 0},
	{Touch: 0},
	{Browser: 0},
	{background_papan_panduan: 0},
	{papan_panduan: 0},
	{isi_panduan: 0},
	{judul_panduan: 0},
	{back: 0},
	{pilih_zona: 0},
	{zona_list: 0},
	{nama_zona: 0},
	{papan_lock: 0},
	{pengunci_konten: 0},
	{papan_unlock: 0},
	{start: 0},
	{papan_alert_pilih_zona: 0},
	{Text_mulai_menu: 0},
	{background_zona1: 0},
	{Solid: 0},
	{pijakan_hidden: 0},
	{Keyboard: 0},
	{Sine: 0},
	{pijakan_tersembunyi: 0},
	{triger_komponen: 0},
	{nextPos: 0},
	{background_main_menu_fiks: 0},
	{close: 0},
	{papan_bundar: 0},
	{judul: 0},
	{gambar_wpp_zona3: 0},
	{gambar_wpp_zona2: 0},
	{gambar_wpp_zona1: 0},
	{background_card_hasil_belajar: 0},
	{bingkai_konten_hasil_belajar: 0},
	{background_konten_hasil_belajar: 0},
	{bintang: 0},
	{judul_skor_hasil_belajar: 0},
	{bingkai_icon_hasil_belajar: 0},
	{judul_petualangan_selesai_hasil_belajar: 0},
	{tombol_hasil_belajar: 0},
	{icon_gunung_hasil_belajar: 0},
	{background_icon_hasil_belajar: 0},
	{ekonomi_hasil_belajar: 0},
	{sayuran_hasil_belajar: 0},
	{hiasan_hasil_belajar_kiri: 0},
	{hiasan_hasil_belajar_kanan: 0},
	{nilai_dataran_tinggi_hasil_belajar: 0},
	{nilai_dataran_rendah_hasil_belajar: 0},
	{judul_tim_hasil_belajar: 0},
	{sub_judul_hasil_belajar: 0},
	{bingkai_materi_hasil_belajar: 0},
	{judulMateriPos: 0},
	{isiMateriPos1: 0},
	{Bullet: 0},
	{"8Direction": 0},
	{burungmainmenu: 0},
	{burung2: 0},
	{burung3: 0},
	{burung4: 0},
	{burung5: 0},
	{burung6: 0},
	{burung7: 0},
	{burung8: 0},
	{burung9: 0},
	{burung10: 0},
	{taniBerbicara: 0},
	{peringatan: 0},
	{teksperingatanzona1: 0},
	{hiasanzona1: 0},
	{hiasanzona2: 0},
	{peringatan2: 0},
	{teksperingatanzona2: 0},
	{triger_komponen2: 0},
	{pijakan_tersembunyi2: 0},
	{papan_pertanyaan_zona1: 0},
	{tutup_jendela_pertanyaan: 0},
	{judul_pertanyaan_zona1: 0},
	{tekspertanyaan: 0},
	{isi_pertanyaan: 0},
	{forward_pertanyaan: 0},
	{forward_pertanyaan2: 0},
	{doni_diam_seragam: 0},
	{doni_diam_petualang: 0},
	{paktanimainmenu: 0},
	{bapakgurumainmenu: 0},
	{Sprite3: 0},
	{next_slide: 0},
	{frame_next_slide: 0},
	{teks_tentang_media: 0},
	{next_slide2: 0},
	{teks_tentang_media2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{BoundTo: 0},
	{karakter: 0},
	{layer1: 0},
	{layer2: 0},
	{layer3: 0},
	{layer4: 0},
	{layer5: 0},
	{layer6: 0},
	{layer7: 0},
	{penutuppapan: 0},
	{isiMateri: 0},
	{nomorPos: 0},
	{posSelesai: 0},
	{teksposinformasi: 0},
	{selesaizona1: 0},
	{papaninformasi1: 0},
	{top_head_karakter: 0},
	{heart_nyawa: 0},
	{soal: 0},
	{frame_nyama: 0},
	{frame_dialog: 0},
	{frame_question: 0},
	{framejawaban: 0},
	{jawaban1huruf: 0},
	{statusJawaban: 0},
	{jawaban1: 0},
	{jawaban1huruf2: 0},
	{jawaban1huruf3: 0},
	{jawaban1huruf4: 0},
	{skor_soal: 0},
	{judulsoal: 0},
	{heart_nyawa2: 0},
	{heart_nyawa3: 0},
	{judullahanpertanian: 0},
	{tekssambutanzona1: 0},
	{jawaban2: 0},
	{jawaban3: 0},
	{jawaban4: 0},
	{lanjutsoal: 0},
	{pesanNPC: 0},
	{postantangan: 0},
	{musikStatus: 0},
	{Nyawa: 0},
	{papanTerakhir: 0},
	{nomorSoal: 0},
	{Skor: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	background_netral: class extends self.ISpriteInstance {},
	papan_main_menu: class extends self.ISpriteInstance {},
	main: class extends self.ISpriteInstance {},
	panduan: class extends self.ISpriteInstance {},
	hasil_belajar: class extends self.ISpriteInstance {},
	tentang_media: class extends self.ISpriteInstance {},
	keluar: class extends self.ISpriteInstance {},
	pusat_bantuan: class extends self.ISpriteInstance {},
	gembok: class extends self.ISpriteInstance {},
	icon_akun: class extends self.ISpriteInstance {},
	nama_profile: class extends self.ISpriteInstance {},
	peringkat: class extends self.ISpriteInstance {},
	pengaturan: class extends self.ISpriteInstance {},
	pesan: class extends self.ISpriteInstance {},
	background_netral_1: class extends self.ISpriteInstance {},
	background_panduan: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	background_papan_panduan: class extends self.ISpriteInstance {},
	papan_panduan: class extends self.ISpriteInstance {},
	isi_panduan: class extends self.ITextInstance {},
	judul_panduan: class extends self.ITextInstance {},
	back: class extends self.ISpriteInstance {},
	pilih_zona: class extends self.ISpriteInstance {},
	zona_list: class extends self.ISpriteInstance {},
	nama_zona: class extends self.ITextInstance {},
	papan_lock: class extends self.ISpriteInstance {},
	pengunci_konten: class extends self.ISpriteInstance {},
	papan_unlock: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	papan_alert_pilih_zona: class extends self.ISpriteInstance {},
	Text_mulai_menu: class extends self.ITextInstance {},
	background_zona1: class extends self.ISpriteInstance {},
	pijakan_hidden: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	pijakan_tersembunyi: class extends self.ISpriteInstance {},
	triger_komponen: class extends self.ISpriteInstance {},
	nextPos: class extends self.ITextInstance {},
	background_main_menu_fiks: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	papan_bundar: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	gambar_wpp_zona3: class extends self.ISpriteInstance {},
	gambar_wpp_zona2: class extends self.ISpriteInstance {},
	gambar_wpp_zona1: class extends self.ISpriteInstance {},
	background_card_hasil_belajar: class extends self.ISpriteInstance {},
	bingkai_konten_hasil_belajar: class extends self.ISpriteInstance {},
	background_konten_hasil_belajar: class extends self.ISpriteInstance {},
	bintang: class extends self.ISpriteInstance {},
	judul_skor_hasil_belajar: class extends self.ITextInstance {},
	bingkai_icon_hasil_belajar: class extends self.ISpriteInstance {},
	judul_petualangan_selesai_hasil_belajar: class extends self.ISpriteInstance {},
	tombol_hasil_belajar: class extends self.ISpriteInstance {},
	icon_gunung_hasil_belajar: class extends self.ISpriteInstance {},
	background_icon_hasil_belajar: class extends self.ISpriteInstance {},
	ekonomi_hasil_belajar: class extends self.ISpriteInstance {},
	sayuran_hasil_belajar: class extends self.ISpriteInstance {},
	hiasan_hasil_belajar_kiri: class extends self.ISpriteInstance {},
	hiasan_hasil_belajar_kanan: class extends self.ISpriteInstance {},
	nilai_dataran_tinggi_hasil_belajar: class extends self.ITextInstance {},
	nilai_dataran_rendah_hasil_belajar: class extends self.ITextInstance {},
	judul_tim_hasil_belajar: class extends self.ITextInstance {},
	sub_judul_hasil_belajar: class extends self.ITextInstance {},
	bingkai_materi_hasil_belajar: class extends self.ISpriteInstance {},
	judulMateriPos: class extends self.ITextInstance {},
	isiMateriPos1: class extends self.ITextInstance {},
	burungmainmenu: class extends self.ISpriteInstance {},
	burung2: class extends self.ISpriteInstance {},
	burung3: class extends self.ISpriteInstance {},
	burung4: class extends self.ISpriteInstance {},
	burung5: class extends self.ISpriteInstance {},
	burung6: class extends self.ISpriteInstance {},
	burung7: class extends self.ISpriteInstance {},
	burung8: class extends self.ISpriteInstance {},
	burung9: class extends self.ISpriteInstance {},
	burung10: class extends self.ISpriteInstance {},
	taniBerbicara: class extends self.ITextInstance {},
	peringatan: class extends self.ISpriteInstance {},
	teksperingatanzona1: class extends self.ITextInstance {},
	hiasanzona1: class extends self.ISpriteInstance {},
	hiasanzona2: class extends self.ISpriteInstance {},
	peringatan2: class extends self.ISpriteInstance {},
	teksperingatanzona2: class extends self.ITextInstance {},
	triger_komponen2: class extends self.ISpriteInstance {},
	pijakan_tersembunyi2: class extends self.ISpriteInstance {},
	papan_pertanyaan_zona1: class extends self.ISpriteInstance {},
	tutup_jendela_pertanyaan: class extends self.ISpriteInstance {},
	judul_pertanyaan_zona1: class extends self.ISpriteInstance {},
	tekspertanyaan: class extends self.ITextInstance {},
	isi_pertanyaan: class extends self.ITextInstance {},
	forward_pertanyaan: class extends self.ISpriteInstance {},
	forward_pertanyaan2: class extends self.ISpriteInstance {},
	doni_diam_seragam: class extends self.ISpriteInstance {},
	doni_diam_petualang: class extends self.ISpriteInstance {},
	paktanimainmenu: class extends self.ISpriteInstance {},
	bapakgurumainmenu: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	next_slide: class extends self.ISpriteInstance {},
	frame_next_slide: class extends self.ISpriteInstance {},
	teks_tentang_media: class extends self.ITextInstance {},
	next_slide2: class extends self.ISpriteInstance {},
	teks_tentang_media2: class extends self.ITextInstance {},
	karakter: class extends self.ISpriteInstance {},
	layer1: class extends self.ISpriteInstance {},
	layer2: class extends self.ISpriteInstance {},
	layer3: class extends self.ISpriteInstance {},
	layer4: class extends self.ISpriteInstance {},
	layer5: class extends self.ISpriteInstance {},
	layer6: class extends self.ISpriteInstance {},
	layer7: class extends self.ISpriteInstance {},
	penutuppapan: class extends self.ISpriteInstance {},
	teksposinformasi: class extends self.ITextInstance {},
	selesaizona1: class extends self.ISpriteInstance {},
	papaninformasi1: class extends self.ISpriteInstance {},
	top_head_karakter: class extends self.ISpriteInstance {},
	heart_nyawa: class extends self.ISpriteInstance {},
	soal: class extends self.ITextInstance {},
	frame_nyama: class extends self.ISpriteInstance {},
	frame_dialog: class extends self.ISpriteInstance {},
	frame_question: class extends self.ISpriteInstance {},
	framejawaban: class extends self.ISpriteInstance {},
	jawaban1huruf: class extends self.ITextInstance {},
	jawaban1: class extends self.ITextInstance {},
	jawaban1huruf2: class extends self.ITextInstance {},
	jawaban1huruf3: class extends self.ITextInstance {},
	jawaban1huruf4: class extends self.ITextInstance {},
	skor_soal: class extends self.ITextInstance {},
	judulsoal: class extends self.ITextInstance {},
	heart_nyawa2: class extends self.ISpriteInstance {},
	heart_nyawa3: class extends self.ISpriteInstance {},
	judullahanpertanian: class extends self.ITextInstance {},
	tekssambutanzona1: class extends self.ITextInstance {},
	jawaban2: class extends self.ITextInstance {},
	jawaban3: class extends self.ITextInstance {},
	jawaban4: class extends self.ITextInstance {},
	lanjutsoal: class extends self.ISpriteInstance {},
	pesanNPC: class extends self.ITextInstance {},
	postantangan: class extends self.ITextInstance {}
}