const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{background_netral: 0},
	{background_main_menu: 0},
	{papan_main_menu: 0},
	{karakter_diam_main_menu: 0},
	{main: 0},
	{panduan: 0},
	{hasil_belajar: 0},
	{tentang_media: 0},
	{keluar: 0},
	{pusat_bantuan: 0},
	{musik: 0},
	{gembok: 0},
	{icon_akun: 0},
	{nama_profile: 0},
	{peringkat: 0},
	{pengaturan: 0},
	{pesan: 0},
	{karakter_pelajar: 0},
	{karakter_receptionist: 0},
	{karakter_bapak_guru: 0},
	{background_netral_1: 0},
	{background_panduan: 0},
	{Touch: 0},
	{Browser: 0},
	{background_papan_panduan: 0},
	{papan_panduan: 0},
	{isi_panduan: 0},
	{judul_panduan: 0},
	{back: 0},
	{pilih_zona: 0},
	{zona_list: 0},
	{nama_zona: 0},
	{papan_lock: 0},
	{pengunci_konten: 0},
	{papan_unlock: 0},
	{start: 0},
	{papan_alert_pilih_zona: 0},
	{Text_mulai_menu: 0},
	{background_zona1: 0},
	{tangga: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{karakter_berjalan: 0},
	{Solid: 0},
	{pijakan_hidden: 0},
	{Keyboard: 0},
	{Sine: 0},
	{pijakan_tersembunyi: 0},
	{tangga_tersembunyi: 0},
	{triger_komponen: 0},
	{nextPos1: 0},
	{background_main_menu_fiks: 0},
	{teks_bantuan: 0},
	{close: 0},
	{papan_bundar: 0},
	{speaker_non_aktif: 0},
	{ornamen_frame: 0},
	{judul: 0},
	{gambar_wpp_zona3: 0},
	{gambar_wpp_zona2: 0},
	{gambar_wpp_zona1: 0},
	{background_card_hasil_belajar: 0},
	{bingkai_konten_hasil_belajar: 0},
	{background_konten_hasil_belajar: 0},
	{bintang: 0},
	{judul_skor_hasil_belajar: 0},
	{bingkai_icon_hasil_belajar: 0},
	{judul_petualangan_selesai_hasil_belajar: 0},
	{tombol_hasil_belajar: 0},
	{icon_gunung_hasil_belajar: 0},
	{background_icon_hasil_belajar: 0},
	{ekonomi_hasil_belajar: 0},
	{sayuran_hasil_belajar: 0},
	{hiasan_hasil_belajar_kiri: 0},
	{hiasan_hasil_belajar_kanan: 0},
	{nilai_dataran_tinggi_hasil_belajar: 0},
	{nilai_dataran_rendah_hasil_belajar: 0},
	{judul_tim_hasil_belajar: 0},
	{sub_judul_hasil_belajar: 0},
	{papan_informasi_pos: 0},
	{bingkai_materi_hasil_belajar: 0},
	{judulMateriPos1: 0},
	{isiMateriPos1: 0},
	{pos1DataranTinggi: 0},
	{Bullet: 0},
	{"8Direction": 0},
	{burung: 0},
	{burung2: 0},
	{burung3: 0},
	{burung4: 0},
	{burung5: 0},
	{burung6: 0},
	{burung7: 0},
	{burung8: 0},
	{burung9: 0},
	{burung10: 0},
	{pakTani: 0},
	{papan_dialog: 0},
	{taniBerbicara: 0},
	{tangga_unik_zona1: 0},
	{monster_zona1: 0},
	{peringatan: 0},
	{teksperingatanzona1: 0},
	{papan_informasi_pos2: 0},
	{pos1DataranTinggi2: 0},
	{hiasanzona1: 0},
	{hiasanzona2: 0},
	{papan_informasi_pos3: 0},
	{pos1DataranTinggi3: 0},
	{monster_zona2: 0},
	{peringatan2: 0},
	{teksperingatanzona2: 0},
	{monster_zona3: 0},
	{monster_zona4: 0},
	{monster_zona5: 0},
	{monster_zona6: 0},
	{papan_informasi_pos4: 0},
	{pos1DataranTinggi4: 0},
	{tangga_tersembunyi2: 0},
	{triger_komponen2: 0},
	{pijakan_tersembunyi2: 0},
	{papan_informasi_pos5: 0},
	{pos1DataranTinggi5: 0},
	{pakTani2: 0},
	{papan_dialog2: 0},
	{papan_pertanyaan_zona1: 0},
	{tutup_jendela_pertanyaan: 0},
	{judul_pertanyaan_zona1: 0},
	{tekspertanyaan: 0},
	{isi_pertanyaan: 0},
	{jawaban_pertama: 0},
	{jawaban_pertama2: 0},
	{jawaban_pertama3: 0},
	{jawaban_pertama4: 0},
	{jawabanA: 0},
	{jawabanA2: 0},
	{jawabanA3: 0},
	{jawabanA4: 0},
	{forward_pertanyaan: 0},
	{forward_pertanyaan2: 0},
	{alert_tutup: 0},
	{kotak_dialog: 0},
	{musikStatus: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	background_netral: class extends self.ISpriteInstance {},
	background_main_menu: class extends self.ISpriteInstance {},
	papan_main_menu: class extends self.ISpriteInstance {},
	karakter_diam_main_menu: class extends self.ISpriteInstance {},
	main: class extends self.ISpriteInstance {},
	panduan: class extends self.ISpriteInstance {},
	hasil_belajar: class extends self.ISpriteInstance {},
	tentang_media: class extends self.ISpriteInstance {},
	keluar: class extends self.ISpriteInstance {},
	pusat_bantuan: class extends self.ISpriteInstance {},
	musik: class extends self.ISpriteInstance {},
	gembok: class extends self.ISpriteInstance {},
	icon_akun: class extends self.ISpriteInstance {},
	nama_profile: class extends self.ISpriteInstance {},
	peringkat: class extends self.ISpriteInstance {},
	pengaturan: class extends self.ISpriteInstance {},
	pesan: class extends self.ISpriteInstance {},
	karakter_pelajar: class extends self.ISpriteInstance {},
	karakter_receptionist: class extends self.ISpriteInstance {},
	karakter_bapak_guru: class extends self.ISpriteInstance {},
	background_netral_1: class extends self.ISpriteInstance {},
	background_panduan: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	background_papan_panduan: class extends self.ISpriteInstance {},
	papan_panduan: class extends self.ISpriteInstance {},
	isi_panduan: class extends self.ITextInstance {},
	judul_panduan: class extends self.ITextInstance {},
	back: class extends self.ISpriteInstance {},
	pilih_zona: class extends self.ISpriteInstance {},
	zona_list: class extends self.ISpriteInstance {},
	nama_zona: class extends self.ITextInstance {},
	papan_lock: class extends self.ISpriteInstance {},
	pengunci_konten: class extends self.ISpriteInstance {},
	papan_unlock: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	papan_alert_pilih_zona: class extends self.ISpriteInstance {},
	Text_mulai_menu: class extends self.ITextInstance {},
	background_zona1: class extends self.ISpriteInstance {},
	tangga: class extends self.ISpriteInstance {},
	karakter_berjalan: class extends self.ISpriteInstance {},
	pijakan_hidden: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	pijakan_tersembunyi: class extends self.ISpriteInstance {},
	tangga_tersembunyi: class extends self.ISpriteInstance {},
	triger_komponen: class extends self.ISpriteInstance {},
	nextPos1: class extends self.ITextInstance {},
	background_main_menu_fiks: class extends self.ISpriteInstance {},
	teks_bantuan: class extends self.ITextInstance {},
	close: class extends self.ISpriteInstance {},
	papan_bundar: class extends self.ISpriteInstance {},
	speaker_non_aktif: class extends self.ISpriteInstance {},
	ornamen_frame: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	gambar_wpp_zona3: class extends self.ISpriteInstance {},
	gambar_wpp_zona2: class extends self.ISpriteInstance {},
	gambar_wpp_zona1: class extends self.ISpriteInstance {},
	background_card_hasil_belajar: class extends self.ISpriteInstance {},
	bingkai_konten_hasil_belajar: class extends self.ISpriteInstance {},
	background_konten_hasil_belajar: class extends self.ISpriteInstance {},
	bintang: class extends self.ISpriteInstance {},
	judul_skor_hasil_belajar: class extends self.ITextInstance {},
	bingkai_icon_hasil_belajar: class extends self.ISpriteInstance {},
	judul_petualangan_selesai_hasil_belajar: class extends self.ISpriteInstance {},
	tombol_hasil_belajar: class extends self.ISpriteInstance {},
	icon_gunung_hasil_belajar: class extends self.ISpriteInstance {},
	background_icon_hasil_belajar: class extends self.ISpriteInstance {},
	ekonomi_hasil_belajar: class extends self.ISpriteInstance {},
	sayuran_hasil_belajar: class extends self.ISpriteInstance {},
	hiasan_hasil_belajar_kiri: class extends self.ISpriteInstance {},
	hiasan_hasil_belajar_kanan: class extends self.ISpriteInstance {},
	nilai_dataran_tinggi_hasil_belajar: class extends self.ITextInstance {},
	nilai_dataran_rendah_hasil_belajar: class extends self.ITextInstance {},
	judul_tim_hasil_belajar: class extends self.ITextInstance {},
	sub_judul_hasil_belajar: class extends self.ITextInstance {},
	papan_informasi_pos: class extends self.ISpriteInstance {},
	bingkai_materi_hasil_belajar: class extends self.ISpriteInstance {},
	judulMateriPos1: class extends self.ITextInstance {},
	isiMateriPos1: class extends self.ITextInstance {},
	pos1DataranTinggi: class extends self.ITextInstance {},
	burung: class extends self.ISpriteInstance {},
	burung2: class extends self.ISpriteInstance {},
	burung3: class extends self.ISpriteInstance {},
	burung4: class extends self.ISpriteInstance {},
	burung5: class extends self.ISpriteInstance {},
	burung6: class extends self.ISpriteInstance {},
	burung7: class extends self.ISpriteInstance {},
	burung8: class extends self.ISpriteInstance {},
	burung9: class extends self.ISpriteInstance {},
	burung10: class extends self.ISpriteInstance {},
	pakTani: class extends self.ISpriteInstance {},
	papan_dialog: class extends self.ISpriteInstance {},
	taniBerbicara: class extends self.ITextInstance {},
	tangga_unik_zona1: class extends self.ISpriteInstance {},
	monster_zona1: class extends self.ISpriteInstance {},
	peringatan: class extends self.ISpriteInstance {},
	teksperingatanzona1: class extends self.ITextInstance {},
	papan_informasi_pos2: class extends self.ISpriteInstance {},
	pos1DataranTinggi2: class extends self.ITextInstance {},
	hiasanzona1: class extends self.ISpriteInstance {},
	hiasanzona2: class extends self.ISpriteInstance {},
	papan_informasi_pos3: class extends self.ISpriteInstance {},
	pos1DataranTinggi3: class extends self.ITextInstance {},
	monster_zona2: class extends self.ISpriteInstance {},
	peringatan2: class extends self.ISpriteInstance {},
	teksperingatanzona2: class extends self.ITextInstance {},
	monster_zona3: class extends self.ISpriteInstance {},
	monster_zona4: class extends self.ISpriteInstance {},
	monster_zona5: class extends self.ISpriteInstance {},
	monster_zona6: class extends self.ISpriteInstance {},
	papan_informasi_pos4: class extends self.ISpriteInstance {},
	pos1DataranTinggi4: class extends self.ITextInstance {},
	tangga_tersembunyi2: class extends self.ISpriteInstance {},
	triger_komponen2: class extends self.ISpriteInstance {},
	pijakan_tersembunyi2: class extends self.ISpriteInstance {},
	papan_informasi_pos5: class extends self.ISpriteInstance {},
	pos1DataranTinggi5: class extends self.ITextInstance {},
	pakTani2: class extends self.ISpriteInstance {},
	papan_dialog2: class extends self.ISpriteInstance {},
	papan_pertanyaan_zona1: class extends self.ISpriteInstance {},
	tutup_jendela_pertanyaan: class extends self.ISpriteInstance {},
	judul_pertanyaan_zona1: class extends self.ISpriteInstance {},
	tekspertanyaan: class extends self.ITextInstance {},
	isi_pertanyaan: class extends self.ITextInstance {},
	jawaban_pertama: class extends self.ISpriteInstance {},
	jawaban_pertama2: class extends self.ISpriteInstance {},
	jawaban_pertama3: class extends self.ISpriteInstance {},
	jawaban_pertama4: class extends self.ISpriteInstance {},
	jawabanA: class extends self.ITextInstance {},
	jawabanA2: class extends self.ITextInstance {},
	jawabanA3: class extends self.ITextInstance {},
	jawabanA4: class extends self.ITextInstance {},
	forward_pertanyaan: class extends self.ISpriteInstance {},
	forward_pertanyaan2: class extends self.ISpriteInstance {}
}